### PR TITLE
Issue #9 - show current git branch

### PR DESCRIPTION
**Pull request by dfelczak**
It shows current git branch name in the header of the project view and It looks like this:

screen shot 2018-06-10 at 20 43 26

### CODE REVIEW

**Comment by kitze** [comment]
Sweet! Thanks @dfelczak.

I'm planning to move all of this info in the footer of the project view tho. I'm gonna work on that today.

**Comment by kitze** [comment]
Wait, why didn't you use the already included `parse-git-config` util?

https://www.npmjs.com/package/parse-git-config

**Comment by dfelczak** [comment]
I was trying use this lib, it provides data about branches, sadly I didn't find any way to get current branch name.

**Comment by kitze** [comment]
Ah okay, thanks anyway it's great!

**Pull request merged**
